jest.setup.ts
package.json
src/components/features/registration/ProviderRegistrationFlow/ProviderRegistrationFlow.tsx
src/lib/sitemap/authentication/index.ts
src/lib/sitemap/index.ts
src/lib/vendors/auth0/client/get-access-token/getAccessToken.ts
src/lib/vendors/auth0/client/get-resource-endpoint/getResourceEndpoint.spec.ts
src/lib/vendors/auth0/client/get-resource-endpoint/getResourceEndpoint.ts
src/lib/vendors/auth0/configuration/configuration.spec.ts
src/lib/vendors/auth0/configuration/configuration.ts
src/pages/_app.tsx
src/pages/api/auth/callback.ts
src/pages/api/auth/login.ts
src/pages/api/auth/logout.ts
src/pages/api/auth/me.ts
src/pages/index.tsx
src/pages/providers/register/success.tsx
yarn.lock

Follows [Auth0 docs](https://auth0.com/docs/quickstart/webapp/nextjs/01-login#configure-auth0) to add Login and Logout to Next.js app.
- I renamed `AUTH0_DOMAIN` to `AUTH0_BACKEND_DOMAIN` in the Auth0 Management API backend app configuration. Initially, I was going to reuse this variable between the management client and the Next auth feature. They share the same value, but come from different apps, so ultimately I decided to separate them. The value is the same only because the apps happen to be in the same Auth0 tenant, not because the apps are _truly_ dependent on the same value.
- In the Auth0 docs, they use the `handleAuth` method in a wildcard `/api/auth/[...auth].ts` file, but this approach would not work for me. All client requests to auth routes returned 404 responses. I solved …

feat: add auth0 login and logout

---

.gitignore
prisma/schema.prisma
src/lib/features/users/get-plan-status/index.ts
src/lib/features/users/get-plan-status/input.ts
src/lib/features/users/get-plan-status/output.ts
src/lib/features/users/get-plan-status/trpc.ts
src/lib/features/users/index.ts
src/lib/server/routers/accounts/resolvers/get-plan-status/index.ts
src/lib/server/routers/accounts/resolvers/get-plan-status/resolver.ts
src/lib/server/routers/accounts/resolvers/index.ts
src/lib/server/routers/accounts/router.ts
src/lib/services/accounts/service/get-plan-status-by-user-id/getPlanStatusByUserId.spec.ts
src/lib/services/accounts/service/get-plan-status-by-user-id/getPlanStatusByUserId.ts
src/lib/services/accounts/service/get-plan-status-by-user-id/index.ts
src/lib/services/accounts/service/index.ts
src/lib/sitemap/index.ts
src/lib/sitemap/onboarding/index.ts
src/pages/index.tsx

Given an Auth0 user id, returns the status of their most recent plan or `null`.
- Feature i/o 
- Resolver + TRPC query
- Accounts service method
- Placeholder UI
- `PlanStatus` enum to the Prisma `Plan` Schema. They follow Stripe's [Subscription statuses](https://stripe.com/docs/api/subscriptions/object#subscription_object-status) 
- One-to-many relations on the Prisma `User` model now plural
NA
Spin up app and login
On login, see yourself get redirected to `/onboarding/billing`. The plan status should be `null` since no plan capturing is implemented yet.
NA
-   [x] …

feat: get plan status by user id

---

src/lib/features/users/get-user-details-by-auth0-id/output.ts
src/lib/services/accounts/service/get-user-details-by-auth0-id/getUserDetailsByAuth0Id.spec.ts
src/lib/services/accounts/service/get-user-details-by-auth0-id/getUserDetailsByAuth0Id.ts
src/lib/sitemap/menus/index.ts
src/lib/sitemap/menus/practice-admin-menu/index.ts
src/lib/sitemap/menus/practice-admin-menu/links.ts
src/lib/sitemap/menus/practice-admin-menu/menu.tsx
src/lib/sitemap/menus/therapist-menu/links.ts
src/lib/sitemap/urls/providers/index.ts
src/lib/sitemap/urls/providers/practice/index.ts
src/pages/index.tsx
src/pages/providers/practice/dashboard.tsx

Adds practice admin support
- menus
- Dashboard page
- check for admin status on user details (`user.id === user.plan.billingUserId`
- Practice URL paths in sitemap
WIP: [Practice Provider invitations](https://trello.com/c/P9ymmEKU)

feat: add practice admin check

---

prisma/migrations/20230211171020_add_new_client_status_to_provider_profile/migration.sql
prisma/schema.prisma
src/lib/modules/accounts/service/service/get-provider-profile-by-user-id/getProviderProfileByUserId.spec.tsx
src/lib/modules/providers/components/ProfileEditor/ProfileEditor.tsx
src/lib/modules/providers/components/ProfileEditor/ui/ProfileEditorForm.tsx
src/lib/modules/providers/components/ProfileEditor/ui/inputs/About/Bio.tsx
src/lib/modules/providers/components/ProfileEditor/ui/inputs/NewClientStatus.tsx
src/lib/modules/providers/components/ProfileEditor/ui/inputs/index.ts

Adds new client status to Provider Profile.
- `newClientStatus` column on `ProviderProfile` model
- `NewClientStatus` enum to `schema.prisma` file
- Prisma migration
- Accepting new client select to profile editor
Also makes Bio a required field
Continued Profile Editor work
Go to editor

feat: add new client status to provider profile

---

src/lib/modules/providers/features/profiles/index.ts
src/lib/modules/providers/features/profiles/update-directory-listing/index.ts
src/lib/modules/providers/features/profiles/update-directory-listing/input.ts
src/lib/modules/providers/features/profiles/update-directory-listing/output.ts
src/lib/modules/providers/features/profiles/update-directory-listing/trpc.ts
src/lib/modules/providers/routes/resolvers/index.ts
src/lib/modules/providers/routes/resolvers/update-directory-listing/index.ts
src/lib/modules/providers/routes/resolvers/update-directory-listing/resolver.ts
src/lib/modules/providers/routes/router.ts
src/lib/modules/providers/service/profiles/index.ts
src/lib/modules/providers/service/profiles/update-directory-listing/index.ts
src/lib/modules/providers/service/profiles/update-directory-listing/updateDirectoryListing.ts
src/pages/providers/practice/profiles/index.tsx

Adds `updateDirectoryListing` funtionality: Feature, providers service method, resolver, and TRPC mutation
Updates Practice Profiles UI to allow `ListingStatus`updates (`listed` and `unlisted`, no `pending` support for now)
- Log in as practice admin and 
- Visit `/providers/practice/profiles`
- List/unlist profiles in the list. 
- 

feat: add directory listing update functionality

---

src/pages/api/auth/logout.ts
src/pages/index.tsx

Initial logins were resulting in a 404 redired. This is because when the index page's server-side routing occurs after initial login,  user would get routed to the appropriate landing page, but that page's RBAC protection would redirect to 404. This is because the role cookie hadn't been set yet. This cookie was getting set on the client side through the `TherifyUser` context so the initial RBAC protect always failed.
Solution: Add a cookie check to the index page's getServerSideProps method and set cookie when not present on first login. 
Adds cookie destruction on the client side Login page, because this page only loads when a user is not present, and in the logout API route.
[Bug: 404 Page in Sign In](https://trello.com/c/z1TFXho5)
Open a new incognito browser window and login to the …

fix: set role cookie on first login

---

src/lib/modules/directory/components/ProviderProfile/ProviderProfile.tsx

Therify Therapist profiles in prod are temporary until we can onboard their respective practices. Because of this, we don't want to misrepresent them as belonging to Therify. 
This PR hides practice details on therapist-designated profiles that belong to Therify's practice
[Trello: Hide practice details on Therify therapist profiles](https://trello.com/c/kZi5ZTt3)
Go to editor as a therify provider and change profile designation to therapist

chore: hide practice on therify therapist profile

---

src/lib/modules/onboarding/components/PracticeDetailsForm/components/inputs/State.tsx
src/lib/modules/onboarding/components/PracticeDetailsForm/components/inputs/ZipCode.tsx
src/lib/modules/providers/components/ProfileEditor/ProfileEditor.tsx

- Adds all state options to `States`select in the practice onboarding form.
- Requires zip code input to be 5 characters in practice onboarding form
- Adds an Alert Toast if profile image upload fails
[States select update](https://trello.com/c/bHYbEzdx)
NA

chore: minor ui improvements

---

src/lib/modules/members/service/get-therify-user-props/getTherifyUserProps.ts
src/lib/modules/members/service/get-therify-user-props/index.ts
src/lib/modules/members/service/index.ts
src/lib/shared/components/ui/Navigation/TopNavigationBar/TopNavigationBar.tsx
src/lib/sitemap/menus/member-menu/links.ts
src/lib/sitemap/urlPaths.ts
src/lib/sitemap/urls/external/index.ts
src/lib/sitemap/urls/members/content/index.ts
src/lib/sitemap/urls/members/index.ts
src/pages/members/content/library.tsx

Turns out, Vimeo does not allow channels to be loaded in an iframe. 
Adds placeholder content page (not used).
Adds an external link to Therify Vimeo account and ability to open in a new window from Top Navigation bar
Adds GetMemberTherifyUserProps for `TODO:` content page
[Content Library](https://trello.com/c/orbmtFLy)
Log in as member and click `Library` in the top bar

chore: add stopgap content library

---

src/lib/modules/accounts/service/service/register-member/transaction/createAuth0User.ts
src/lib/modules/accounts/service/service/register-provider-with-invitation/transaction/createAuth0User.ts
src/lib/modules/accounts/service/service/register-provider/transaction/createAuth0User.ts
src/lib/modules/registration/components/MemberRegistrationSuccess/MemberRegistrationSuccess.tsx
src/lib/modules/registration/components/ProviderRegistrationSuccess/ProviderRegistrationSuccess.tsx

- Comments out Auth0 email language and functionality on registration success pages. 
- sets `verify_email` param `false` when creating auth0 user in registrations
[Remove Auth0 Email Verification](https://trello.com/c/F10ZIMaJ)
Register

chore: remove auth0 email verification

---

src/lib/modules/directory/components/ProviderProfile/ProviderProfile.tsx
src/lib/shared/components/features/pages/TopNavigationPage/TopNavigationPage.tsx
src/lib/shared/components/ui/Navigation/NavigationDrawer/NavigationDrawer.tsx
src/lib/shared/components/ui/Navigation/NavigationMenu/NavListItem.tsx
src/lib/shared/components/ui/Navigation/utils/getNavigtionIcon.tsx
src/lib/shared/components/ui/Typography/Miscellaneous/Caption/index.tsx
src/lib/sitemap/menus/member-menu/links.ts
src/lib/sitemap/menus/member-menu/menu.tsx
src/lib/sitemap/types/navigationIcon.ts
src/lib/sitemap/types/navigationLink.ts

- Removes "Licensed in {Licensed States}" sub header on coach profiles
- Moves "Therify Website" link to secondary menu
- Adds external link icon when nav link is marked `external`. 
- Adds Therify Icon to nav icons
- Adds first name and "`['Member' | 'Coach' | 'Therapist' | 'Practice Owner']` since `{user.createdAt year}`" header in mobile menu 
- Moves position of Favorite button in profile
---
---
---

chore: minor post launch ui updates

---

src/lib/modules/providers/service/profiles/create-provider-profile-for-practice/transaction/createProviderProfile.ts
src/lib/modules/providers/service/profiles/get-profile-by-id/getProfileById.ts
src/lib/modules/providers/service/profiles/get-profile-by-user-id/getProfileByUserId.ts
src/lib/modules/providers/service/profiles/update-provider-profile/updateProviderProfile.ts
src/lib/shared/types/provider-profile/providerProfile.spec.ts
src/lib/shared/types/provider-profile/providerProfile.ts

Supervisor data was getting omitted by profile schema validation. This allows supervisor data to be validated and saved.
Prisma does not allow JSON types to save `null` as its value. However, because the supervisor column was getting saved without a default value, the initial value in the db was `null`. After a supervisor had been set on the profile in the db, the only way to remove it now is to set the value to '{}' to satisfy the `JSON` type. 
Our application layer wants the supervisor property to be nullable in our ProviderProfile. Therefore, now we must transform that empty JSON object value to be `null` when adapting the supervisor database schema to an application schema and that `null` supervisor back to `{}` when adapting back. 
This adaption to the nullable application type now …

fix: solve stripping supervisor from profile

---

src/lib/modules/directory/features/update-connection-request-status/input.ts
src/lib/modules/directory/service/update-connection-request-status/updateConnectionRequestStatus.ts
src/lib/shared/components/features/pages/ProviderClientListPage/ProviderClientListPage.tsx
src/lib/shared/components/ui/Modal/DisplayModal.tsx
src/pages/providers/coach/clients.tsx
src/pages/providers/therapist/clients.tsx

Improves provider clients ui 
- Removes reimbursement request link when a connection status is not `accepted`
- Adds message input to accept modal
- Shows Account name in table view
- Shows account name and covered sessions in member details modal
[Provider Clients Page Improvements](https://trello.com/c/mngq0ysD)
N/A

chore: provider clients page improvements

---

prisma/migrations/20230228074118_add_terminated_connection_status/migration.sql
prisma/schema.prisma
src/lib/modules/providers/components/Clients/ActionConfirmationModal/ActionConfirmationModal.tsx
src/lib/modules/providers/components/Clients/ActionConfirmationModal/index.ts
src/lib/modules/providers/components/Clients/ClientList/ClientList.tsx
src/lib/modules/providers/components/Clients/ClientList/index.ts
src/lib/modules/providers/components/Clients/ClientList/ui/ActionButtons.tsx
src/lib/modules/providers/components/Clients/ClientList/ui/ClientListItem.tsx
src/lib/modules/providers/components/Clients/ClientList/ui/ListCells.tsx
src/lib/modules/providers/components/Clients/ClientList/ui/index.ts
src/lib/modules/providers/components/Clients/MemberDetailsModal/MemberDetailsModal.tsx
src/lib/modules/providers/components/Clients/MemberDetailsModal/index.ts
src/lib/modules/providers/components/Clients/index.ts
src/lib/modules/providers/components/hooks/index.ts
src/lib/modules/providers/components/hooks/useProviderConnectionRequests.ts
src/lib/shared/components/features/pages/PracticeClientListPage/PracticeClientListPage.tsx
src/lib/shared/components/features/pages/ProviderClientListPage/ProviderClientListPage.tsx
src/lib/shared/components/ui/Typography/Paragraph/index.tsx
src/lib/sitemap/menus/therapist-menu/menu.tsx
src/pages/providers/coach/clients.tsx
src/pages/providers/practice/clients.tsx
src/pages/providers/practice/profiles/index.tsx
src/pages/providers/therapist/clients.tsx

Adds termination connection request status and UI support to terminate clients.
Refactors Therapist and Coach client pages to reuse the same UI

feat: add termination to connection request

---

src/lib/modules/directory/features/provider-search/input.ts
src/lib/modules/directory/features/provider-search/output.ts
src/lib/modules/directory/service/execute-provider-search/executeProviderSearch.spec.ts
src/lib/modules/directory/service/execute-provider-search/executeProviderSearch.ts
src/lib/modules/directory/service/execute-provider-search/index.ts
src/lib/modules/directory/service/index.ts
src/lib/modules/members/service/get-directory-page-props/getDirectoryPageProps.ts

As more practices onboard, we are now showing directory results to members that they cannot connect with because of state restrictions.  This work adds `executeDirectorySearch` method that takes a state and filters down results.
- must have directoryListing.status of `listed`
- Must be connected to a practice that has an active plan. 
- "Active" is defined as a plan with `status` set to either `active` or `trialing`, with a `startDate` that is in the past, and an `endDate` that is in the future
- Must also have at least one credential where `credential.state === input.state` and `credential.expirationDate` is in the future
NA
Observe directory behavior
-   [ ] …

chore: v1 directory results filtering

---

src/lib/shared/vendors/stripe/types/discount.ts
src/lib/shared/vendors/stripe/types/subscription.ts

The stripe webhook listener for `customer.subscription.updated` failed for 2 events. 
The issue: 
This fix makes `subscription.discount.discount` optional and `subscription.default_payment_method` nullable

fix: update unexpected stripe subscription types

---

src/lib/modules/directory/service/update-connection-request-status/updateConnectionRequestStatus.ts
src/lib/modules/providers/components/Clients/ClientList/ui/ClientListItem.tsx
src/lib/shared/components/features/pages/PracticeClientListPage/PracticeClientListPage.tsx

Claire brought to our attention that this functionality can break client confidentiality. This PR removes the ability to terminate a connection request
NA

fix: remove ability to terminate connection request

---

src/lib/modules/directory/components/ProviderProfile/ProviderProfile.tsx
src/lib/modules/messaging/components/Chat/Chat.tsx
src/lib/modules/messaging/components/Chat/index.ts
src/lib/modules/messaging/components/Chat/useRemoveHubspotChatWidget.ts
src/lib/modules/providers/components/Clients/ClientList/ClientList.tsx
src/lib/modules/providers/components/Clients/ClientList/ui/ActionButtons.tsx
src/lib/modules/providers/components/Clients/ClientList/ui/ClientListItem.tsx
src/lib/modules/providers/components/ProfileEditor/ui/inputs/Practice/ToggleInputs.tsx
src/lib/modules/providers/components/ProfileEditor/ui/inputs/Practice/index.tsx
src/lib/modules/providers/service/page-props/get-clients-page-props/getProviderClientsPageProps.ts
src/lib/modules/providers/service/page-props/get-practice-clients-page-props/getPracticeClientsPageProps.ts
src/lib/shared/components/features/pages/ProviderClientListPage/ProviderClientListPage.tsx
src/lib/shared/components/styles/Global.tsx
src/lib/shared/components/ui/Containers/ApplicationContainer/ApplicationContainer.tsx
src/lib/sitemap/menus/coach-menu/menu.tsx
src/lib/sitemap/menus/member-menu/links.ts
src/lib/sitemap/menus/practice-admin-menu/menu.tsx
src/lib/sitemap/menus/therapist-menu/menu.tsx
src/pages/members/chat.tsx
src/pages/providers/coach/chat.tsx
src/pages/providers/coach/profiles.tsx
src/styles/globals.css

Ui clean up for Chat Launch
Adds
- Removes chat buttons on Clients page
- In-app messaging callouts on provider profile
- Change `Content Library` to `Library` in the Member menu
- Removes HubSpot widget when coach or member loads chat page
- Fixes the Webkit `100vh` overflow issue
- Fixes Chat menu disappearing on Coach Profiles page
- Adds New feature badge  by Messaging toggle in Profile Editor
- Removes environment flags protection
[Trello V1 chat finishing touches for launch](https://trello.com/c/LVp7cnkL)
-   [ ] I have updated …

chore: v1 chat cleanup

---

src/lib/modules/messaging/components/Chat/useRemoveHubspotChatWidget.ts

A bad use of useEffect was causing infinite rerenders and breaking the chat experience.
This cleans up the useEffect.
Got to the chat page and view the console. 

fix: infinite chat re-renders from HubSpot widget removal

---

src/lib/modules/notifications/components/context/Provider.tsx
src/lib/modules/notifications/components/hooks/index.ts
src/lib/modules/notifications/components/hooks/use-in-app-presence/index.ts
src/lib/modules/notifications/components/hooks/use-in-app-presence/useInAppPresence.ts
src/lib/modules/notifications/service/get-user-presence/getUserPresenceFactory.ts
src/lib/modules/notifications/service/get-user-presence/index.ts
src/lib/modules/notifications/service/in-app/create/createInAppNotification.ts
src/lib/modules/notifications/service/in-app/utils/withAdminAuthentication.ts
src/lib/modules/notifications/service/index.ts
src/lib/shared/context/firebase/Provider.tsx
src/lib/shared/vendors/firebase/getFirebaseVendor.ts
src/lib/shared/vendors/firebase/methods/index.ts
src/lib/shared/vendors/firebase/methods/presence/constants.ts
src/lib/shared/vendors/firebase/methods/presence/establish-presence/establishPresence.ts
src/lib/shared/vendors/firebase/methods/presence/establish-presence/index.ts
src/lib/shared/vendors/firebase/methods/presence/index.ts
src/lib/shared/vendors/firebase/methods/presence/read-presence/index.ts
src/lib/shared/vendors/firebase/methods/presence/read-presence/readPresence.ts
src/lib/shared/vendors/firebase/methods/presence/set-presence/index.ts
src/lib/shared/vendors/firebase/methods/presence/set-presence/setPresence.ts
src/lib/shared/vendors/firebase/methods/sign-out/signOut.ts
src/lib/sitemap/urls/api/index.ts
src/lib/sitemap/urls/authentication/index.ts
src/pages/logout.tsx

Extends firebaseVendor to support tracking user presence in Firebase.
- Adds `readPresenceFactory`,`establishPresence`, and `setPresenceFactory` methods to Firebase Vendor
- Adds `useInAppPresence` hook
- Adds `getUserPresence` method to `Notifications Service`
Note: Refactors user Logout and Firebase sign-in/signout to more reliably keep firebase auth sessions in line with Auth0 auth sessions.
- Adds`Logout` page to clean up clientside authentication (sign out of firebase, set presence to `offline`, and clear cookies) before redirecting to Auth0's `api/auth/logout` route.
- Changes Sitemap's `URL_PATHS.AUTH.LOGOUT` path to be `/logout` so all existing logout navigation will go to new logout page.
[Trello: Firebase Presence](https://trello.com/c/TLwKjeHf)
- Go to Firebase Realtime …

feat: add firebase presence

---

src/lib/modules/accounts/service/service/handle-practice-onboarding/transaction/createStripeCheckoutSession.ts
src/lib/modules/onboarding/components/PracticeDetailsForm/PracticeDetailsForm.tsx
src/lib/modules/onboarding/components/PracticeDetailsForm/components/inputs/BillingCycleButtons.tsx
src/lib/modules/onboarding/components/PracticeDetailsForm/components/inputs/index.ts
src/lib/modules/onboarding/components/PracticeDetailsForm/hooks/usePracticeOnboardingStorage.ts
src/lib/modules/onboarding/features/handle-practice-onboarding/input.ts
src/lib/modules/webhooks/services/stripe/event-handlers/invoices/paid/handlers/handleGroupPracticePayment.ts
src/lib/shared/types/products/products.ts
src/pages/providers/onboarding/billing/index.tsx

This allows practice owners to sign up for annual plans.
- Adds Stripe price id
- Updates practice onboarding form
- Updates `handlePracticeOnboarding` to take a `billingCycle` param and apply the correct Stripe priceId to the checkout session.
[Stripe: Add annual subscription](https://trello.com/c/VmwEoZMZ)
Sign up as a new practice
Manually tested webhook integration with Stipes test environment and local Stripe CLI wehook listeners

feat: add annual subscriptions

---

src/lib/shared/components/features/pages/providers/billing-page-view/ui/PracticeAdminBillingView.tsx

Adds plans details for practice owner billing page

chore: add plan info to practice billing view

---

src/lib/shared/components/features/error-boundary/ErrorBoundary.tsx
src/lib/shared/components/features/error-boundary/ErrorFallback.tsx
src/lib/shared/components/features/error-boundary/index.ts
src/pages/500.tsx
src/pages/_app.tsx

This adds an error boundary to the app to gracefully handle clientside unhandled exceptions
[Error Boundary](https://trello.com/c/NNCrMi0M)

feat: add error boundary

---

package.json
src/lib/shared/hooks/index.ts
src/lib/shared/hooks/use-feature-flags/index.ts
src/lib/shared/hooks/use-feature-flags/useFeatureFlags.ts
src/lib/shared/types/feature-flags/featureFlags.ts
src/lib/shared/types/feature-flags/index.ts
src/lib/shared/types/index.ts
src/pages/_app.tsx
yarn.lock

- Adds LaunchDarkly's React library as dependency
- Adds `useFeatureFlags` hook
- Adds `FeatureFlags` to `shared/types`
[Trello: Feature Flags integration](https://trello.com/c/rZvPFRbP)
- log flags. 
- Go to LaunchDarkly dashboard and add the signed in user to the coaches segment
- See the flag change

feat: add feature flags

---

src/lib/shared/components/features/pages/ProviderNavigationPage/ProviderNavigationPage.tsx
src/lib/shared/types/feature-flags/featureFlags.spec.ts
src/lib/shared/types/feature-flags/featureFlags.ts
src/lib/sitemap/menus/coach-menu/menu.tsx
src/pages/providers/coach/chat.tsx
src/pages/providers/coach/payments.tsx

Hides Stripe Connect feature when `flags.hasStripeConnectAccess` is false
Adds `didFlagsLoad` flag
Merges partially valid flags with default flags when validating feature flag objects
N/A

chore: feat flag stripe connect

---

src/lib/modules/providers/components/ProfileEditor/ProfileEditor.tsx
src/lib/modules/providers/components/ProfileEditor/ui/ProfileEditorForm.tsx
src/pages/providers/practice/profiles/create.tsx
src/pages/providers/practice/profiles/editor/[profileId].tsx
src/pages/providers/therapist/profile/editor.tsx

Adds `allowProfileDesignationChange` and `canEditSessionPrice` controls to the profile editor.
- Profile designation (`coach` vs `therapist`) can only be edited at profile creation. This scopes it only to practice owners that can set a profile designation.
- Coach profiles can no longer edit their session price in the profile editor by non-practice owners. Coaching Prices can only be edited in the practice owner's profile editor.
- Therapist profiles can still edit session pricing in the editor by non-practice owners.
-   [ ] I have …

chore: add profile designation and price editing rules

---

src/lib/modules/accounts/components/hooks/index.ts
src/lib/modules/accounts/components/hooks/use-session-invoicing/index.ts
src/lib/modules/accounts/components/hooks/use-session-invoicing/useSessionInvoicing.tsx
src/lib/modules/messaging/components/Chat/ui/ChatActions.tsx
src/lib/modules/providers/components/Clients/ClientList/ClientList.tsx
src/lib/modules/providers/components/Clients/ClientList/ui/ClientListItem.tsx
src/lib/shared/components/features/pages/ProviderClientListPage/ProviderClientListPage.tsx
src/pages/providers/coach/clients.tsx

Moves session invoicing to reusable hook
Uses hook in Chat and Client views
N/A
Ensure feature flag is on an Stripe onboarding has started. Then view Clients action list to create invoice

chore: reuse invoicing from chat in clients ui

---

src/lib/modules/accounts/features/billing/handle-membership-plan-payment/index.ts
src/lib/modules/accounts/features/billing/handle-membership-plan-payment/input.ts
src/lib/modules/accounts/features/billing/handle-membership-plan-payment/output.ts
src/lib/modules/accounts/features/billing/index.ts
src/lib/modules/accounts/service/service/billing/billingFactory.ts
src/lib/modules/accounts/service/service/billing/handle-membership-plan-payment/handleMembershipPlanPayment.ts
src/lib/modules/accounts/service/service/billing/handle-membership-plan-payment/index.ts
src/lib/modules/accounts/service/service/billing/handle-membership-plan-payment/transaction/createInvoiceEntity.ts
src/lib/modules/accounts/service/service/billing/handle-membership-plan-payment/transaction/createPlanEntity.ts
src/lib/modules/accounts/service/service/billing/handle-membership-plan-payment/transaction/definition.ts
src/lib/modules/accounts/service/service/billing/handle-membership-plan-payment/transaction/getAccount.ts
src/lib/modules/accounts/service/service/billing/handle-membership-plan-payment/transaction/index.ts
src/lib/modules/webhooks/services/stripe/event-handlers/invoices/paid/handleInvoicePaid.ts
src/lib/modules/webhooks/services/stripe/event-handlers/invoices/paid/handlers/handleMembershipPayment.ts
src/lib/modules/webhooks/services/stripe/event-handlers/invoices/paid/handlers/index.ts
src/lib/shared/types/products/products.ts

Adds webhook and `accounts.billing` service support to identify and handle plan payments.
- Adds `invoice.paid` handler logic to identify membership payments 
- Hands membership payments to `accounts.billing.handleMembershipPlanPayment` method
- Creates membership plans
Create plans

chore: handle membership payments

---

src/lib/modules/directory/features/provider-search/input.ts
src/lib/modules/directory/service/execute-provider-search/executeProviderSearch.spec.ts
src/lib/modules/directory/service/execute-provider-search/executeProviderSearch.ts
src/lib/modules/directory/service/generate-recommendations/generateRecommendations.ts
src/lib/modules/members/service/get-directory-page-props/getDirectoryPageProps.ts
src/lib/sitemap/menus/member-menu/links.ts
src/lib/sitemap/menus/member-menu/menu.tsx
src/pages/members/account/billing.tsx

When a member signs up as an individual plan holder (a plan with 1 seat), they should not have access to therapists. 
- Checks plan.seats before allowing therapis profiles in directory and self-assessment results
- Minor UI improvements on member billing page

chore: remove therapy results from individuals plan

---

src/lib/shared/emitter/emitter.spec.ts
src/lib/shared/emitter/emitter.ts

Define base event emitter. This will be the foundational component of the revamped notification service. 

chore: define base emitter

---

src/lib/modules/accounts/service/billing/handle-reimbursement-submission/transaction/claimSession.ts
src/lib/modules/accounts/service/billing/handle-reimbursement-submission/transaction/definition.ts
src/lib/modules/accounts/service/billing/handle-reimbursement-submission/transaction/getProviderDetails.ts
src/lib/modules/directory/service/list-connection-requests-by-practice-owner-id/listConnectionRequestsByPracticeOwnerId.ts
src/lib/modules/directory/service/list-connection-requests-by-provider-id/listConnectionRequestsByProviderId.ts
src/lib/modules/providers/components/Clients/ClientList/ui/ClientListItem.tsx
src/lib/modules/providers/components/Clients/MemberDetailsModal/MemberDetailsModal.tsx
src/lib/modules/providers/components/Clients/utils/getCoveredSessionsMessage.ts
src/lib/modules/providers/components/Clients/utils/index.ts
src/lib/shared/components/features/pages/PracticeClientListPage/PracticeClientListPage.tsx
src/lib/shared/types/connection-request/connectionRequest.ts
src/pages/api/dev/create-redeemed-session.ts
src/pages/api/dev/remove-connected-stripe-account.ts

- Adds `remainingSessions` to Connection Requests. 
- Improves `Clients` UI to communicate remaining sessions
- Disables reimbursement request action list item when no remaining sessions.
- Adds `{baseUrl}/api/dev/create-redeemed-session` endpoint to manually create a redeemed session
NA

chore: calculate remaining sessions

---

src/lib/shared/components/features/pages/SideNavigationPage/SideNavigationPage.tsx
src/lib/shared/components/features/pages/TopNavigationPage/TopNavigationPage.tsx
src/lib/shared/components/ui/Banner/Banner.spec.tsx
src/lib/shared/components/ui/Banner/Banner.stories.tsx
src/lib/shared/components/ui/Banner/Banner.tsx
src/lib/shared/components/ui/Banner/index.ts
src/lib/shared/components/ui/Layout/SideNavigationLayout/SideNavigationLayout.spec.tsx
src/lib/shared/components/ui/Layout/SideNavigationLayout/SideNavigationLayout.tsx
src/lib/shared/components/ui/Layout/TopNavigationLayout/TopNavigationLayout.spec.tsx
src/lib/shared/components/ui/Layout/TopNavigationLayout/index.tsx
src/lib/shared/components/ui/index.ts
src/lib/shared/types/feature-flags/featureFlags.ts

Adds Feature flag driven Banner solution
- Adds `Banner` shared UI component
- Adds `bannerContent` JSON feature flag
- Adds Banners to Sidenavigation layout and top navigation layout pages
Banner content feature flage schema: 
```
bannerContent: z.object({
message: z.string().optional(),
color: z.string().optional(),
linkUrl: z.string().optional(),
linkText: z.string().optional(),
}),
```
To render a banner, a new banner content object will need to be added as a variation to the Launch Darkly feature flag.
After the variation is added, you can add rule to evaluate when and to whom that content should be shown. 
-   [ ] Breaking change (change that is not …

feat: add banner UI

---

src/lib/shared/types/address/canada/province.ts
src/lib/shared/types/provider-profile/providerProfile.ts
src/lib/shared/utils/format-reimbursement-request-url/formatReimbursementRequestUrl.spec.ts
src/lib/shared/utils/format-reimbursement-request-url/formatReimbursementRequestUrl.ts

- Adds `British columbia` as a Canadian province option
- Fixes prefill for Canadian province on reimbursement request Jotform URL

chore: add British Columbia + reimbursement prefill improvements

---

src/lib/modules/accounts/features/billing/create-stripe-billing-portal-session/index.ts
src/lib/modules/accounts/features/billing/create-stripe-billing-portal-session/input.ts
src/lib/modules/accounts/features/billing/create-stripe-billing-portal-session/output.ts
src/lib/modules/accounts/features/billing/create-stripe-billing-portal-session/trpc.ts
src/lib/modules/accounts/features/billing/index.ts
src/lib/modules/accounts/routes/resolvers/create-stripe-billing-portal-session/index.ts
src/lib/modules/accounts/routes/resolvers/create-stripe-billing-portal-session/resolver.ts
src/lib/modules/accounts/routes/resolvers/index.ts
src/lib/modules/accounts/routes/router.ts
src/lib/modules/accounts/service/billing/billingFactory.ts
src/lib/modules/accounts/service/billing/create-stripe-billing-portal-session/createStripeBillingPortalSession.ts
src/lib/modules/accounts/service/billing/create-stripe-billing-portal-session/index.ts
src/lib/shared/vendors/stripe/client/create-billing-portal-session/createBillingPortalSession.ts
src/lib/shared/vendors/stripe/client/create-billing-portal-session/index.ts
src/lib/shared/vendors/stripe/client/create-billing-portal-session/schema/index.ts
src/lib/shared/vendors/stripe/client/create-billing-portal-session/schema/input.ts
src/lib/shared/vendors/stripe/client/create-billing-portal-session/schema/output.ts
src/lib/shared/vendors/stripe/index.ts
src/pages/members/account/billing.tsx

Adds Stripe billing portal access to dtc members. Also creates billing portal sessions so members no longer need email links from Stripe to log in.
1. Login as a DTC member. 
2. go to the billing page.
3. Click the "Launch Stripe Customer Portal" button

feat: member plan management

---

package.json
src/lib/shared/types/feature-flags/featureFlags.ts
src/lib/shared/vendors/launchdarkly/configuration.ts
src/lib/shared/vendors/launchdarkly/index.ts
src/lib/shared/vendors/launchdarkly/methods/create-context-from-user/createContextFromUser.ts
src/lib/shared/vendors/launchdarkly/methods/create-context-from-user/index.ts
src/lib/shared/vendors/launchdarkly/methods/get-flag-for-context/getFlagForContext.ts
src/lib/shared/vendors/launchdarkly/methods/get-flag-for-context/index.ts
src/lib/shared/vendors/launchdarkly/methods/index.ts
yarn.lock

Integrates LaunchDarkly's Node SDK to facilitate server-side feature flagging.
https://www.notion.so/Add-Server-Side-Feature-Flags-c827b0e9586844baba6dacb8a5282f78?pvs=4
Add this code snippet to any server side function with access to a `TherifyUser` object
``` 
const hasAccess = await launchDarklyVendor.getFlagForContext(
FeatureFlags.SERVER_FLAGS.DID_FLAGS_LOAD,
launchDarklyVendor.createContextFromUser(user)
);
console.log({ hasAccess });
```
NA

chore: add launchdarkly vendor

---

src/lib/modules/messaging/components/Chat/Chat.tsx
src/lib/modules/messaging/hooks/use-chat/index.ts
src/lib/modules/messaging/hooks/use-chat/useChatClient.tsx
src/lib/shared/components/features/account/MemberExpiredPlanPage/MemberExpiredPlanPage.spec.tsx
src/lib/shared/components/features/pages/MemberNavigationPage/MemberNavigationPage.tsx
src/lib/shared/components/features/pages/ProviderNavigationPage/ProviderNavigationPage.tsx
src/lib/shared/components/features/pages/SideNavigationPage/SideNavigationPage.tsx
src/lib/shared/components/features/pages/TopNavigationPage/TopNavigationPage.tsx
src/lib/shared/components/ui/IconButtonWithBadge/IconButtonWithBadge.tsx
src/lib/shared/components/ui/IconButtonWithBadge/index.ts
src/lib/shared/components/ui/IconWithBadge/index.ts
src/lib/shared/components/ui/Navigation/NavigationDrawer/NavigationDrawer.tsx
src/lib/shared/components/ui/Navigation/SecondaryNavigationControls/SecondaryNavigationControls.tsx
src/lib/shared/components/ui/Navigation/SecondaryTopBar/SecondaryTopBar.tsx
src/lib/shared/components/ui/Navigation/TopNavigationBar/TopNavigationBar.tsx
src/lib/shared/components/ui/index.ts

This work moves StreamChat's `Chat` provider to the layout page level and passes unread message information into the navigation components. This allows the navigation layout to render unread message notifications for the messaging route.

feat: show unread chat notification badges

---

src/lib/modules/webhooks/services/stream-chat/errors/UnknownStreamChatEvent.ts
src/lib/modules/webhooks/services/stream-chat/errors/index.ts
src/lib/modules/webhooks/services/stream-chat/event-handlers/handleEvent.ts
src/lib/modules/webhooks/services/stream-chat/event-handlers/messages/index.ts
src/lib/modules/webhooks/services/stream-chat/event-handlers/messages/newMessage.ts
src/lib/modules/webhooks/services/stream-chat/index.ts
src/lib/modules/webhooks/services/stream-chat/schema/basePushEventSchema.ts
src/lib/modules/webhooks/services/stream-chat/schema/index.ts
src/lib/modules/webhooks/services/stream-chat/schema/newMessageEventSchema.ts
src/lib/modules/webhooks/services/stream-chat/service.ts
src/lib/modules/webhooks/services/stream-chat/webhookParams.ts
src/lib/shared/vendors/stream-chat/index.ts
src/lib/shared/vendors/stream-chat/verify-webhook-signature/index.ts
src/lib/shared/vendors/stream-chat/verify-webhook-signature/schema/index.ts
src/lib/shared/vendors/stream-chat/verify-webhook-signature/schema/input.ts
src/lib/shared/vendors/stream-chat/verify-webhook-signature/verifyWebhookSignature.ts
src/pages/api/webhooks/stream-chat.ts

Adds Stream Chat webhook listener for the `message.new` event.
- Handles event and validates signature
- Identifies `message.new` events and routes to handler
- Extracts Therify users from event and pulls recipient presence from our Notifications Service
*Follow up work needed to handle notification when users are offline.
Spin up local tunnel (`yarn localtunnel`)
Set your tunnel URL in the Steam Chat dashboard
Send a message to an offline user and watch the console.
Needs follow-up notification work …

feat: add streamchat webhook handler

---

src/lib/modules/providers/components/Clients/ClientDetails/ClientDetails.tsx
src/lib/modules/providers/components/Clients/ClientDetails/ui/ProfileDetails.tsx

This PR adds functionality to allow coaches to report inaccurate remaining sessions. It also no longer hides the invoice button based on remaining sessions. Finally, it includes a few minor UI styling improvements.
[Demo Video](https://www.loom.com/share/27696831962c4940aea0ef5aaa590d81?sid=c12c9361-f556-4f43-81b9-d033ce83d1d0)

chore: improve client page for release

---

src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.stories.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/index.ts
src/lib/shared/components/ui/FormElements/FormRenderer/types.ts
src/lib/shared/components/ui/FormElements/index.ts

Moves `title` and `subtitle` from `FormRendererProps` to `FormConfig` object. Exports FormRenderer and types from shared UI library.

chore: improve form renderer

---

src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.stories.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/getFormInput.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/ui/InputField.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/ui/PasswordField.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/ui/SelectField.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/ui/TextAreaField.tsx

Refactors the use of the `register` function from the `useFrom` hook to use `Controller` element from react-hook-form.
Also disables input fields when form is submitting.
This solves some unexpected validation behavior. 

refactor: hook-form controller over register fn

---

src/lib/shared/components/ui/FormElements/RadioSelect/RadioSelect.spec.tsx
src/lib/shared/components/ui/FormElements/RadioSelect/RadioSelect.stories.tsx
src/lib/shared/components/ui/FormElements/RadioSelect/RadioSelect.tsx
src/lib/shared/components/ui/FormElements/RadioSelect/index.ts
src/lib/shared/components/ui/FormElements/index.ts

Adds `RadioSelect` form element to shared UI library
[Radio Select Form Element](https://www.notion.so/Radio-Select-Form-Element-41ab0d7cbef34129bb780846818b2cd5?pvs=4)
`yarn storybook`
View `Components > RadioSelect`

feat: add radio select form element

---

src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.stories.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/RadioSelectField.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/getFormInput.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/types.ts
src/lib/shared/components/ui/FormElements/FormRenderer/ui/RadioSelectField.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/ui/TextAreaField.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/ui/ToggleField.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/ui/index.ts

Add `RadioSelectField` to form renderer
[Add Radio Select FormRenderer field](https://www.notion.so/Add-Radio-Select-FormRenderer-field-a838ff8a1c2b4feca28e2fbf861ad8db?pvs=4)
Run `yarn storybook`
View `Ui/FormElements/FormRenderer`

feat: add radio select to form renderer

---

src/lib/shared/hooks/use-feature-flags/useFeatureFlags.ts
src/lib/shared/types/feature-flags/featureFlags.spec.ts
src/lib/shared/types/feature-flags/featureFlags.ts

Adds feature flag to toggle on v3 experience. Flag added as `is-v3-directory-enabled`.
Additionally, renames some schema and validation functions to better communicate they only apply to client-side flag validation. This is an oversight from when server side flags were introduced. The naming was a little confusing.
- ~~defaultFlags~~ ->  defaultClientFlags
- ~~schema~~ -> clientFlagsSchema
- ~~Type~~ -> ClientFlagsType
- ~~isValid~~ -> isValidClientFlags
- ~~validate~~ -> validateClientFlags
N/A
Check feature flags loaded from LaunchDarkly
-   [ ] I have tested this …

chore: add v3 feature flag + naming improvements

---

src/lib/modules/care/components/CareJumbotron/CareJumbotron.spec.tsx
src/lib/modules/care/components/CareJumbotron/CareJumbotron.tsx

Update the priority of different states passed to the `CareJumbotron`. The gist of it is that when the `hasRecommendationsForReview` prop is true, the `CareJumbotron` will display the celebration background/style, overriding any other props passed in.
None, just a small refactor. But related to [Care-Screen-Jumbotron](https://www.notion.so/Care-Screen-Jumbotron-4df6d765a5244e23add5f7ce022c0464?pvs=4)
Run `yarn test` and `yarn storybook`

refactor: care jumbotron state priority

---

src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.spec.tsx
src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.stories.tsx
src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.tsx
src/lib/modules/accounts/components/settings/SettingsPage/index.ts
src/lib/modules/accounts/components/settings/SettingsPage/utils/getSettingsTabView.spec.ts
src/lib/modules/accounts/components/settings/SettingsPage/utils/getSettingsTabView.ts
src/lib/modules/accounts/components/settings/SettingsPage/utils/index.ts
src/lib/modules/accounts/components/settings/index.ts
src/lib/shared/components/ui/Tabs/index.tsx
src/pages/members/account/settings/[view].tsx

- Adds page to display `SettingsPage`
- Adds `SettingsPage` component
[Setting Tabs Page](https://www.notion.so/Settings-Tabs-Page-f5d22e0da7574d88b89e7ff767d8f28e?pvs=4)
Storybook 

feat: add v3 settings page

---

src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.spec.tsx
src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.stories.tsx
src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.tsx
src/lib/modules/accounts/components/settings/SettingsPage/views/AccountView/AccountView.spec.tsx
src/lib/modules/accounts/components/settings/SettingsPage/views/AccountView/AccountView.tsx
src/lib/modules/accounts/components/settings/SettingsPage/views/AccountView/form/config.ts
src/lib/modules/accounts/components/settings/SettingsPage/views/AccountView/form/index.ts
src/lib/modules/accounts/components/settings/SettingsPage/views/AccountView/form/schema.ts
src/lib/modules/accounts/components/settings/SettingsPage/views/AccountView/index.ts
src/lib/modules/accounts/components/settings/SettingsPage/views/AccountView/ui/ImageUploadButton.tsx
src/lib/modules/accounts/components/settings/SettingsPage/views/index.ts
src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/DateField.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/FormRenderer.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/InputField.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/PasswordField.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/RadioSelectField.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/Select.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/TelephoneField.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/TextareaField.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/__tests__/ToggleField.spec.tsx
src/lib/shared/components/ui/FormElements/FormRenderer/types.ts
src/pages/members/account/settings/[view].tsx

- Adds Account view to v3 member settings page + unit tests
- Makes Form Title optional
- Passes `reset` function to `FormRenderer`'s `onSubmit` handler to allow form's `dirty` and `touched` states to reset after submitting prefilled results on the Settings page.
- Adds unit test for form reset
[V3 Setting: Account View](https://www.notion.so/V3-Settings-Account-View-55443d42f41745568a622be79051d246?pvs=4)
1. Spin up the app locally
2. Login as a member (with v3 feature flag turned on)
3. Visit `http://localhost:3000/members/account/settings/account`
-   [x] I have …

feat: add v3 account settings view
