- .github/dependabot.yml
- .github/mergify.yml
configure dependabot and mergify
Closes THE-18
> chore: configure mergify and dependabot

- package.json
- src/lib/vendors/stripe/client/construct-event/constructEvent.ts
- src/lib/vendors/stripe/client/construct-event/index.ts
- src/lib/vendors/stripe/index.ts
- src/pages/api/webhooks/stripe.ts
- yarn.lock
This PR if introduced, will add a webhook handler for Stripe. Note, this does not have actually handling behavior. 
> feat: Stripe Webhook Handler

- src/components/ui/Navigation/TopNavigationBar/TopNavigationBar.tsx
- src/lib/context/firebase/Provider.tsx
- src/lib/context/therify-user/Context.ts
- src/lib/context/therify-user/Provider.tsx
- src/lib/features/users/get-user-details-by-auth0-id/output.ts
- src/lib/hooks/use-therify-user/useTherifyUser.ts
- src/lib/server/routers/accounts/resolvers/get-user-details-by-auth0-id/resolver.ts
- src/lib/services/accounts/service/get-user-details-by-auth0-id/getUserDetailsByAuth0Id.spec.ts
- src/lib/services/accounts/service/get-user-details-by-auth0-id/getUserDetailsByAuth0Id.ts
- src/pages/_app.tsx
- src/pages/index.tsx
- src/pages/members/home.tsx
- src/pages/providers/coach/dashboard.tsx
- src/pages/providers/onboarding/billing/success.tsx
- src/pages/providers/therapist/dashboard.tsx
Refactors `useTherifyUser` hook and `TherifyUser` context.
Moves TRPC query to TherifyUser Provider and uses the `useTherifyUser` hook to access the context.
Also moves firebase user authentication to the Firebase Provider
[Trello Card: User Context / useTherifyUser Hook](https://trello.com/c/2eNCi4gl)
Spin up app and login to observe user being read.
NA
Finally, a smaller PR
> refactor: use therify user hook

- src/lib/features/provider-profiles/get-provider-profile-by-user-id/index.ts
- src/lib/features/provider-profiles/get-provider-profile-by-user-id/input.ts
- src/lib/features/provider-profiles/get-provider-profile-by-user-id/output.ts
- src/lib/features/provider-profiles/get-provider-profile-by-user-id/trpc.ts
- src/lib/features/provider-profiles/index.ts
- src/lib/hooks/use-provider-profile/index.ts
- src/lib/hooks/use-provider-profile/useProviderProfile.ts
- src/lib/server/routers/accounts/resolvers/get-provider-profile-by-user-id/index.ts
- src/lib/server/routers/accounts/resolvers/get-provider-profile-by-user-id/resolver.ts
- src/lib/server/routers/accounts/resolvers/index.ts
- src/lib/server/routers/accounts/router.ts
- src/lib/services/accounts/service/get-provider-profile-by-user-id/getProviderProfileByUserId.spec.tsx
- src/lib/services/accounts/service/get-provider-profile-by-user-id/getProviderProfileByUserId.ts
- src/lib/services/accounts/service/get-provider-profile-by-user-id/index.ts
- src/lib/services/accounts/service/index.ts
Set up `useProviderProfile` hook
- `GetProviderProfileByUserId` Feature schema 
- Service method
- resolver
- `useProviderProfile` hook
[Trello Card: useProviderProfile Hook](https://trello.com/c/qyrUmq5N)
1. Create profile
2. add hook to a page
3. visit page and log profile
N/A
> feat: add use provider profile hook

- src/components/features/directory/DirectoryCard/DirectoryCard.tsx
- src/components/features/pages/MemberNavigationPage/MemberNavigationPage.tsx
- src/components/features/pages/MemberNavigationPage/index.ts
- src/components/features/pages/SideNavigationPage/SideNavigationPage.tsx
- src/components/features/pages/TopNavigationPage/TopNavigationPage.tsx
- src/components/ui/Navigation/NavigationDrawer/NavigationDrawer.tsx
- src/components/ui/Navigation/SecondaryNavigationControls/SecondaryNavigationControls.tsx
- src/components/ui/Navigation/TopNavigationBar/TopNavigationBar.tsx
- src/lib/server/context.ts
- src/lib/services/members/get-directory-page-props/getDirectoryPageProps.ts
- src/lib/services/members/get-directory-page-props/index.ts
- src/lib/services/members/get-directory-profile-props/getDirectoryProfileProps.tsx
- src/lib/services/members/get-directory-profile-props/index.ts
- src/lib/services/members/get-home-page-props/getHomePageProps.ts
- src/lib/services/members/get-home-page-props/index.ts
- src/lib/services/members/index.ts
- src/lib/services/notifications/index.ts
- src/lib/services/webhooks/stripe/index.ts
- src/lib/sitemap/menus/member-menu/links.ts
- src/lib/sitemap/urls/directory/index.ts
- src/lib/sitemap/urls/members/index.ts
- src/lib/types/index.ts
- src/lib/types/therify-user/index.ts
- src/lib/types/therify-user/therifyUser.ts
- src/pages/members/directory.tsx
- src/pages/members/directory/[profileId].tsx
- src/pages/members/home.tsx
> feat: member pages

- package.json
- src/components/features/directory/ProviderProfile/CalloutBanner/CalloutBanner.stories.tsx
- src/components/features/directory/ProviderProfile/CalloutBanner/CalloutBanner.tsx
- src/components/features/directory/ProviderProfile/CalloutBanner/index.ts
- src/components/features/directory/ProviderProfile/ProviderProfile.stories.tsx
- src/components/features/directory/ProviderProfile/ProviderProfile.tsx
- src/components/features/media/MediaUploadWidget.tsx
- src/components/features/media/hooks/userCloudinaryWidget.ts
- src/components/features/providers/ProfileEditor/ProfileEditor.stories.tsx
- src/components/features/providers/ProfileEditor/ProfileEditor.tsx
- src/components/features/providers/ProfileEditor/ui/inputs/Designation.tsx
- src/components/features/providers/ProfileEditor/ui/inputs/Image/index.tsx
- src/components/features/providers/ProfileEditor/ui/inputs/Practice/ToggleInputs.tsx
- src/components/ui/Avatar/index.tsx
- src/lib/types/provider-supervisor/providerSupervisor.ts
Adds missing fields to provider profile. Improves some styling issues. 
[WIP Practice Provider invitations](https://trello.com/c/P9ymmEKU)
`yarn storybook`
Visit Therapist page: `http://localhost:6006/?path=/story/components-features-directory-providerprofile--therapist-profile`
visit Coach page: `http://localhost:6006/?path=/story/components-features-directory-providerprofile--coach-profile`
-------
-------
> chore: update provider profile

- src/components/features/media/hooks/userCloudinaryWidget.ts
- src/components/features/providers/ProfileEditor/ProfileEditor.tsx
- src/components/features/providers/ProfileEditor/ui/ProfileEditorForm.tsx
- src/components/ui/Modal/index.tsx
- src/lib/hooks/use-on-screen/index.ts
- src/lib/sitemap/urls/providers/practice/index.ts
- src/pages/_document.tsx
- src/pages/providers/practice/profiles/create.tsx
- src/pages/providers/practice/profiles/index.tsx
Adds Profile create page at `/providers/practice/profiles/create`. Also improves mobile editor experience (adds drawer preview)
[WIP Practice Provider Invitations](https://trello.com/c/P9ymmEKU)
Login as practice admin. 
Visit `/providers/practice/profiles/create`
> feat: setup create profile page + mobile updates

- src/emails/previews/JoinPractice.tsx
- src/lib/modules/providers/components/ProfileEditor/ProfileEditor.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/ProfileEditorForm.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/SupervisorInput/SupervisorForm.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/SupervisorInput/index.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/SupervisorInput/inputs/ExpirationDate.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/SupervisorInput/inputs/LicenseNumber.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/SupervisorInput/inputs/Name.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/SupervisorInput/inputs/NpiNumber.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/SupervisorInput/inputs/StateSelect.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/SupervisorInput/inputs/index.ts
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Credentials/index.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/IdentitySection/index.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Pricing/MaximumRate.tsx
- src/lib/modules/registration/components/MemberRegistrationFlow/ui/inputs/EmailAddress.tsx
- src/lib/modules/registration/components/MemberRegistrationFlow/ui/inputs/GivenName.tsx
- src/lib/modules/registration/components/MemberRegistrationFlow/ui/inputs/Insurance.tsx
- src/lib/modules/registration/components/MemberRegistrationFlow/ui/inputs/Password.tsx
- src/lib/modules/registration/components/MemberRegistrationFlow/ui/inputs/PasswordConfirmation.tsx
- src/lib/modules/registration/components/MemberRegistrationFlow/ui/inputs/State.tsx
- src/lib/modules/registration/components/MemberRegistrationFlow/ui/inputs/Surname.tsx
- src/lib/modules/registration/components/ProviderRegistrationFlow/ui/ProviderRegistrationForm/inputs/EmailAddress.tsx
- src/lib/modules/registration/components/ProviderRegistrationFlow/ui/ProviderRegistrationForm/inputs/GivenName.tsx
- src/lib/modules/registration/components/ProviderRegistrationFlow/ui/ProviderRegistrationForm/inputs/Password.tsx
- src/lib/modules/registration/components/ProviderRegistrationFlow/ui/ProviderRegistrationForm/inputs/PasswordConfirmation.tsx
- src/lib/modules/registration/components/ProviderRegistrationFlow/ui/ProviderRegistrationForm/inputs/Surname.tsx
- src/lib/shared/components/ui/FormElements/Input/Input.tsx
- src/lib/shared/components/ui/FormElements/Select/index.tsx
- src/lib/shared/types/provider-supervisor/providerSupervisor.ts
- src/pages/providers/practice/profiles/create.tsx
Adds supervisor input.
Fixes use of `fullWidth` in inputs
NA
Go to editor and toggle on "Ar
> feat: add supervisor input

- src/lib/modules/providers/service/page-props/get-billing-page-props/getBillingPageProps.ts
- src/lib/modules/providers/service/page-props/get-billing-page-props/index.ts
- src/lib/modules/providers/service/page-props/index.ts
- src/lib/shared/components/features/pages/ProviderNavigationPage/ProviderNavigationPage.tsx
- src/lib/shared/components/features/pages/ProviderNavigationPage/index.ts
- src/lib/shared/components/ui/Navigation/NavigationMenu/NavigationMenu.spec.tsx
- src/lib/sitemap/menus/coach-menu/menu.tsx
- src/lib/sitemap/menus/member-menu/menu.tsx
- src/lib/sitemap/menus/practice-admin-menu/menu.tsx
- src/lib/sitemap/menus/therapist-menu/menu.tsx
- src/lib/sitemap/urls/providers/coaches/index.ts
- src/lib/sitemap/urls/providers/therapists/index.ts
- src/pages/index.tsx
- src/pages/providers/account/billing.tsx
- src/pages/providers/coach/profiles.tsx
- src/pages/providers/therapist/profiles.tsx
Adds layout to billing page
Adds therapist/coach `profiles` page
Removes menu links that are not included in launch
[Trello: Remove Pages](https://trello.com/c/MYA4l7V5)
> chore: add billing page layout + provider landing pages

- src/lib/modules/messaging/components/Chat/Chat.tsx
Fixes some small style issues: 
- updates CSS color variables
- Makes mobile channel list a drawer on mobile
- Fixes desktop chat input width
- Adds ChannelHeader
- 
> chore: update chat styling

- src/lib/modules/accounts/routes/resolvers/handle-account-onboarding/index.ts
- src/lib/modules/accounts/routes/resolvers/handle-account-onboarding/resolver.ts
- src/lib/modules/accounts/routes/resolvers/index.ts
- src/lib/modules/accounts/routes/router.ts
- src/lib/modules/accounts/service/service/handle-account-onboarding/handleAccountOnboarding.ts
- src/lib/modules/accounts/service/service/handle-account-onboarding/index.ts
- src/lib/modules/accounts/service/service/handle-account-onboarding/transaction/createStripeCheckoutSession.ts
- src/lib/modules/accounts/service/service/handle-account-onboarding/transaction/defendAgainstDuplicatePlans.ts
- src/lib/modules/accounts/service/service/handle-account-onboarding/transaction/definition.ts
- src/lib/modules/accounts/service/service/handle-account-onboarding/transaction/getUserDetails.ts
- src/lib/modules/accounts/service/service/handle-account-onboarding/transaction/handleAccountEntity.ts
- src/lib/modules/accounts/service/service/handle-account-onboarding/transaction/index.ts
- src/lib/modules/accounts/service/service/index.ts
- src/lib/modules/onboarding/features/handle-account-onboarding/trpc.ts
- src/lib/shared/vendors/stripe/client/create-checkout-session/createCheckoutSession.ts
- src/lib/shared/vendors/stripe/client/create-checkout-session/schema/input.ts
- src/lib/sitemap/urls/members/account/index.ts
- src/lib/sitemap/urls/members/index.ts
- src/lib/sitemap/urls/members/onboarding/index.ts
Adds Accounts service method and TRPC resolver to handle account onboarding.
- Gets user details
- Creates or updates account details
- Ensure plan does not already exits
- Creates a checkout session for the Account owner
- Adds TRPC mutation + resolver
> chore: handle account onboarding

- prisma/migrations/20230419172342_add_practice_to_redeemed_session/migration.sql
- prisma/migrations/20230419173822_remove_cascade_delete_on_redeemed_sessions/migration.sql
- prisma/schema.prisma
- src/lib/modules/directory/service/execute-provider-search/executeProviderSearch.ts
Adds practice relation to redeemed sessions table
Makes Provider Profile relation nullable
removes cascade delete from provider profiles and practices
> chore: add practice relation to redeemed sessions

- src/lib/modules/directory/features/create-connection-request/errors/index.ts
- src/lib/modules/directory/features/create-connection-request/errors/memberProfileNotFound.ts
- src/lib/modules/directory/features/create-connection-request/errors/providerProfileNotFound.ts
- src/lib/shared/errors/base-error/baseError.spec.ts
- src/lib/shared/errors/base-error/baseError.ts
- src/lib/shared/errors/base-error/index.ts
- src/lib/shared/errors/http-error/httpError.spec.ts
- src/lib/shared/errors/http-error/httpError.ts
- src/lib/shared/status-codes/index.ts
- src/lib/shared/status-codes/statusCodes.ts
This PR if merged will add a shared base error type. Features should expose expected errors which extend either BaseError or HTTPError respectively. 
> Chore Custom Errors

- src/lib/modules/providers/components/Clients/ReimbursementModal/ReimbursementModal.tsx
- src/lib/modules/providers/components/Clients/ReimbursementModal/index.ts
- src/lib/modules/providers/components/Clients/index.ts
- src/lib/shared/components/features/pages/PracticeClientListPage/PracticeClientListPage.tsx
- src/lib/shared/components/features/pages/ProviderClientListPage/ProviderClientListPage.tsx
- src/lib/shared/types/feature-flags/featureFlags.ts
- src/lib/shared/utils/format-reimbursement-request-url/formatReimbursementRequestUrl.spec.ts
- src/lib/shared/utils/format-reimbursement-request-url/formatReimbursementRequestUrl.ts
- src/pages/providers/practice/clients.tsx
Adds an Iframe modal showing the JotForm reimbursement form.
Adds feature flag to toggle on iframe
> refactor: iframe reimbursement requests

- package.json
- prisma/migrations/20230427190354_add_video_url_to_provider_profile/migration.sql
- prisma/schema.prisma
- src/lib/modules/directory/components/ProviderProfile/ProviderProfile.tsx
- src/lib/modules/directory/components/ProviderProfile/ProviderVideo/ProviderVideo.stories.tsx
- src/lib/modules/directory/components/ProviderProfile/ProviderVideo/ProviderVideo.tsx
- src/lib/modules/directory/components/ProviderProfile/ProviderVideo/index.ts
- src/lib/modules/media/components/MediaUploadWidget.stories.tsx
- src/lib/modules/media/components/MediaUploadWidget.tsx
- src/lib/modules/media/components/hooks/userCloudinaryWidget.ts
- src/lib/modules/providers/components/ProfileEditor/ProfileEditor.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/ProfileEditorForm.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/Video/index.tsx
- src/lib/modules/providers/components/ProfileEditor/ui/inputs/index.ts
- src/lib/shared/components/ui/VideoPlayer/VideoPlayer.tsx
- src/lib/shared/components/ui/VideoPlayer/Videoplayer.stories.tsx
- src/lib/shared/components/ui/VideoPlayer/index.ts
- src/lib/shared/types/__mocks__/providerProfile.ts
- src/lib/shared/types/provider-profile/generate-random-profile/generateRandomProfile.ts
- yarn.lock
This PR if merged will add videos to provider profiles. 
Providers can add a video to their profile by editing their profile and using the new video upload widget. 
> Feat Video Player

- prisma/migrations/20230607161216_add_dtc_memeber_role/migration.sql
- prisma/schema.prisma
- src/lib/modules/accounts/routes/resolvers/index.ts
- src/lib/modules/accounts/routes/resolvers/register-dtc-member/index.ts
- src/lib/modules/accounts/routes/resolvers/register-dtc-member/resolver.ts
- src/lib/modules/accounts/routes/router.ts
- src/lib/modules/accounts/service/index.ts
- src/lib/modules/accounts/service/register-dtc-member/index.ts
- src/lib/modules/accounts/service/register-dtc-member/registerDTCMember.ts
- src/lib/modules/accounts/service/register-dtc-member/transaction/assignAuth0Role.ts
- src/lib/modules/accounts/service/register-dtc-member/transaction/createAuth0User.ts
- src/lib/modules/accounts/service/register-dtc-member/transaction/createStripeCustomer.ts
- src/lib/modules/accounts/service/register-dtc-member/transaction/createTherifyUserEntity.ts
- src/lib/modules/accounts/service/register-dtc-member/transaction/definition.ts
- src/lib/modules/accounts/service/register-dtc-member/transaction/index.ts
- src/lib/modules/accounts/service/register-dtc-member/transaction/updateUserEntity.ts
- src/lib/modules/onboarding/components/AccountDetailsForm/AccountDetailsForm.tsx
- src/lib/modules/registration/components/MemberRegistrationFlow/MemberRegistrationFlow.tsx
- src/lib/modules/registration/features/index.ts
- src/lib/modules/registration/features/register-dtc-member/index.ts
- src/lib/modules/registration/features/register-dtc-member/input.ts
- src/lib/modules/registration/features/register-dtc-member/output.ts
- src/lib/modules/registration/features/register-dtc-member/trpc.ts
- src/lib/shared/hooks/use-plan-monitoring/usePlanMonitoring.ts
- src/pages/accounts/onboarding/billing/index.tsx
- src/pages/index.tsx
- src/pages/members/onboarding/billing/index.tsx
- src/pages/members/onboarding/billing/success.tsx
- src/pages/register.tsx
Adds a registration page for members to sign up solely for individual accounts. adds onboarding flow for payment as well
> feat: DTC Registration

- package.json
- src/lib/modules/scheduling/components/Scheduler/Scheduler.stories.tsx
- src/lib/modules/scheduling/components/Scheduler/Scheduler.tsx
- src/lib/modules/scheduling/components/Scheduler/SchedulerDrawer.tsx
- src/lib/modules/scheduling/components/Scheduler/SchedulerWidget.tsx
- src/lib/modules/scheduling/components/Scheduler/__mocks__/timeSlots.ts
- src/lib/modules/scheduling/components/Scheduler/index.ts
- src/lib/modules/scheduling/components/Scheduler/types/index.ts
- src/lib/modules/scheduling/components/Scheduler/ui/DateColumn/DateColumn.tsx
- src/lib/modules/scheduling/components/Scheduler/ui/DateColumn/index.ts
- src/lib/modules/scheduling/components/Scheduler/ui/index.ts
- src/lib/modules/scheduling/components/index.ts
- yarn.lock
Adds scheduler ui.
- Scheduler
- Scheduler drawer
- Scheduler Widget
> feat: add scheduler ui

- src/lib/modules/scheduling/features/index.ts
- src/lib/modules/scheduling/features/remove-calendar-access/index.ts
- src/lib/modules/scheduling/features/remove-calendar-access/input.ts
- src/lib/modules/scheduling/features/remove-calendar-access/output.ts
- src/lib/modules/scheduling/features/remove-calendar-access/trpc.ts
- src/lib/modules/scheduling/routes/resolvers/index.ts
- src/lib/modules/scheduling/routes/resolvers/remove-calendar-access/index.ts
- src/lib/modules/scheduling/routes/resolvers/remove-calendar-access/resolver.ts
- src/lib/modules/scheduling/routes/router.ts
- src/lib/modules/scheduling/service/index.ts
- src/lib/modules/scheduling/service/remove-calendar-access/index.ts
- src/lib/modules/scheduling/service/remove-calendar-access/removeCalendarAccess.ts
- src/pages/providers/coach/scheduling/index.tsx
Adds service method and trpc route to remove/delete calendar access.
> feat: remove calendar access

- src/lib/shared/types/feature-flags/featureFlags.ts
- src/pages/providers/coach/scheduling/index.tsx
Protects scheduling work-in-progress behing feature flag. 
flag: `is-coach-scheduling-enabled`
> chore: feature flag coach scheduling

- src/lib/modules/messaging/components/chat-ui/ChannelList/ChannelList.stories.tsx
- src/lib/modules/messaging/components/chat-ui/ChannelList/ChannelList.tsx
- src/lib/modules/messaging/components/chat-ui/ChannelList/index.ts
- src/lib/modules/messaging/components/chat-ui/ChannelList/ui/Channel.tsx
- src/lib/modules/messaging/components/chat-ui/ChannelList/ui/ChannelTabs.tsx
- src/lib/modules/messaging/components/chat-ui/ChatWindow/ChatWindow.stories.tsx
- src/lib/modules/messaging/components/chat-ui/ChatWindow/ChatWindow.tsx
- src/lib/modules/messaging/components/chat-ui/ChatWindow/index.ts
- src/lib/modules/messaging/components/chat-ui/MessageGroup/MessageGroup.stories.tsx
- src/lib/modules/messaging/components/chat-ui/MessageGroup/MessageGroup.tsx
- src/lib/modules/messaging/components/chat-ui/MessageGroup/MessageName/MessageName.tsx
- src/lib/modules/messaging/components/chat-ui/MessageInput/MessageInput.tsx
- src/lib/modules/messaging/components/chat-ui/types.ts
- src/lib/modules/messaging/components/chat-ui/utils/generateMessageGroups.spec.ts
- src/lib/modules/messaging/components/chat-ui/utils/generateMessageGroups.ts
- src/lib/shared/components/ui/Avatar/index.tsx
Updates Messaging components. Adds Channel list and chat window components.
> feat: update v3 chat components

- src/lib/shared/components/ui/FormElements/DatePicker/DatePicker.tsx
- src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.spec.tsx
- src/lib/shared/components/ui/FormElements/FormRenderer/FormRenderer.stories.tsx
- src/lib/shared/components/ui/FormElements/FormRenderer/getFormInput.tsx
- src/lib/shared/components/ui/FormElements/FormRenderer/types.ts
- src/lib/shared/components/ui/FormElements/FormRenderer/ui/DatePickerField.tsx
- src/lib/shared/components/ui/FormElements/FormRenderer/ui/index.ts
Adds and tests Date picker input
> feat: add date picker field to form renderer

- src/lib/modules/notifications/components/context/Provider.tsx
- src/lib/modules/notifications/components/ui/NotificationDrawer/NotificationDrawer.tsx
- src/lib/shared/components/features/pages/MemberNavigationPage/MemberNavigationPage.spec.tsx
- src/lib/shared/components/features/pages/MemberNavigationPage/MemberNavigationPage.tsx
- src/lib/shared/components/features/pages/v3/TopNavigationPage/TopNavigationPage.spec.tsx
- src/lib/shared/components/features/pages/v3/TopNavigationPage/TopNavigationPage.tsx
- src/lib/shared/components/features/pages/v3/TopNavigationPage/index.ts
- src/lib/shared/components/features/pages/v3/index.ts
- src/lib/shared/components/ui/Navigation/NavigationDrawer/NavigationDrawer.tsx
- src/lib/shared/components/ui/Navigation/v3/SecondaryNavigationControls/SecondaryNavigationControls.spec.tsx
- src/lib/shared/components/ui/Navigation/v3/SecondaryNavigationControls/SecondaryNavigationControls.tsx
- src/lib/shared/components/ui/Navigation/v3/TopNavigationBar/TopNavigationBar.tsx
- src/lib/shared/components/ui/Navigation/v3/index.ts
- src/lib/sitemap/menus/member-menu/links.ts
- src/lib/sitemap/menus/member-menu/menu.tsx
- src/lib/sitemap/urls/members/account/account-settings.ts
- src/lib/sitemap/urls/members/account/index.ts
- src/lib/sitemap/urls/members/index.ts
- Adds Top Navigation layout
- Adds Member Navigation page
- Tests The layout and member page
[](https://www.notion.so/Member-Page-Layout-07c29a0d9244472084d70c6bdc878ad1?pvs=4)
Start app
Turn `isV3DirectoryEnabled` flag on to see the updated layout
> feat: v3 top navigation layout page

- src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.spec.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.stories.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/AccountView/ui/ImageUploadButton.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/CareDetailsView.spec.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/CareDetailsView.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/form/config.ts
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/form/index.ts
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/form/schema.ts
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/index.ts
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/ui/InsuranceForm.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/ui/PlanBadge.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/ui/PlanDetails.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/ui/ShareCard.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/CareDetailsView/ui/index.ts
- src/lib/modules/accounts/components/settings/SettingsPage/views/ui/UnderLinedButton.tsx
- src/lib/shared/utils/test-utils/navigatorMock.ts
- src/pages/members/account/settings/[view].tsx
Adds v3 care details view and unit tests
[V3 Settings: Care Details View](https://www.notion.so/V3-Settings-Care-Details-View-9353126c5c2e4f30a76e4f6c81e335d3?pvs=4)
Spin up local app
Log in as member with v3 feature flag access
Go to `http://localhost:3000/members/account/settings/care-details`
> feat: v3 care details settings view

- src/lib/modules/accounts/components/settings/SettingsPage/SettingsPage.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/BillingView/BillingView.spec.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/BillingView/BillingView.tsx
- src/lib/modules/accounts/components/settings/SettingsPage/views/BillingView/index.ts
- src/lib/modules/accounts/components/settings/SettingsPage/views/index.ts
- src/pages/members/account/settings/[view].tsx
Adds v3 Billing and Payments view and unit tests
[V3 Settings: Billing & Payments View](https://www.notion.so/V3-Settings-Billing-Payments-View-d84fd8d8f0704315ba2c57291a965d15?pvs=4)
Spin it up and look
`http://localhost:3000/members/account/settings/billing`
> feat: v3 settings billing & payments view
